version: "3.2"

services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - djongo_tutorial_mongodb_data:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped

    redis:
        image: redis:alpine

volumes:
  djongo_tutorial_mongodb_data: